/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-max-black-df17520841214c1792fb8a44c6783ee7
Title: Apple iPhone 15 Pro Max Black
*/
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { PhoneModel } from "../types/consts.types";
import { FC, useEffect } from "react";

interface ModelProps {
	scale: [number, number, number];
	item: Omit<PhoneModel, "id">;
	size: "small" | "large";
}

const Model: FC<ModelProps> = props => {
	const { nodes, materials } = useGLTF("/models/scene.glb");

	const texture = useTexture(props.item.img);

	useEffect(() => {
		Object.entries(materials).map(material => {
			if (
				material[0] !== "zFdeDaGNRwzccye" &&
				material[0] !== "ujsvqBWRMnqdwPx" &&
				material[0] !== "hUlRcbieVuIiOXG" &&
				material[0] !== "jlzuBkUzuJqgiAK" &&
				material[0] !== "xNrofRCqOXXHVZt"
			) {
				// @ts-ignore
				material[1].color = new THREE.Color(props.item.color[0]);
			}
			material[1].needsUpdate = true;
		});
	}, [materials, props.item]);

	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.ttmRoLdJipiIOmf instanceof THREE.Mesh
						? nodes.ttmRoLdJipiIOmf.geometry
						: undefined
				}
				material={materials.hUlRcbieVuIiOXG}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.DjsDkGiopeiEJZK instanceof THREE.Mesh
						? nodes.DjsDkGiopeiEJZK.geometry
						: undefined
				}
				material={materials.PaletteMaterial001}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.buRWvyqhBBgcJFo instanceof THREE.Mesh
						? nodes.buRWvyqhBBgcJFo.geometry
						: undefined
				}
				material={materials.PaletteMaterial002}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.MrMmlCAsAxJpYqQ_0 instanceof THREE.Mesh
						? nodes.MrMmlCAsAxJpYqQ_0.geometry
						: undefined
				}
				material={materials.dxCVrUCvYhjVxqy}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.wqbHSzWaUxBCwxY_0 instanceof THREE.Mesh
						? nodes.wqbHSzWaUxBCwxY_0.geometry
						: undefined
				}
				material={materials.MHFGNLrDQbTNima}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.QvGDcbDApaGssma instanceof THREE.Mesh
						? nodes.QvGDcbDApaGssma.geometry
						: undefined
				}
				material={materials.kUhjpatHUvkBwfM}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.vFwJFNASGvEHWhs instanceof THREE.Mesh
						? nodes.vFwJFNASGvEHWhs.geometry
						: undefined
				}
				material={materials.RJoymvEsaIItifI}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.evAxFwhaQUwXuua instanceof THREE.Mesh
						? nodes.evAxFwhaQUwXuua.geometry
						: undefined
				}
				material={materials.KSIxMqttXxxmOYl}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.USxQiqZgxHbRvqB instanceof THREE.Mesh
						? nodes.USxQiqZgxHbRvqB.geometry
						: undefined
				}
				material={materials.mcPrzcBUcdqUybC}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.TvgBVmqNmSrFVfW instanceof THREE.Mesh
						? nodes.TvgBVmqNmSrFVfW.geometry
						: undefined
				}
				material={materials.pIhYLPqiSQOZTjn}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.GuYJryuYunhpphO instanceof THREE.Mesh
						? nodes.GuYJryuYunhpphO.geometry
						: undefined
				}
				material={materials.eShKpuMNVJTRrgg}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.pvdHknDTGDzVpwc instanceof THREE.Mesh
						? nodes.pvdHknDTGDzVpwc.geometry
						: undefined
				}
				material={materials.xdyiJLYTYRfJffH}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.CfghdUoyzvwzIum instanceof THREE.Mesh
						? nodes.CfghdUoyzvwzIum.geometry
						: undefined
				}
				material={materials.jpGaQNgTtEGkTfo}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.DjdhycfQYjKMDyn instanceof THREE.Mesh
						? nodes.DjdhycfQYjKMDyn.geometry
						: undefined
				}
				material={materials.ujsvqBWRMnqdwPx}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.usFLmqcyrnltBUr instanceof THREE.Mesh
						? nodes.usFLmqcyrnltBUr.geometry
						: undefined
				}
				material={materials.sxNzrmuTqVeaXdg}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.xXDHkMplTIDAXLN instanceof THREE.Mesh
						? nodes.xXDHkMplTIDAXLN.geometry
						: undefined
				}
				material={materials.pIJKfZsazmcpEiU}
				scale={0.01}>
				<meshStandardMaterial
					roughness={1}
					map={texture}
				/>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.vELORlCJixqPHsZ instanceof THREE.Mesh
						? nodes.vELORlCJixqPHsZ.geometry
						: undefined
				}
				material={materials.zFdeDaGNRwzccye}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.EbQGKrWAqhBHiMv instanceof THREE.Mesh
						? nodes.EbQGKrWAqhBHiMv.geometry
						: undefined
				}
				material={materials.TBLSREBUyLMVtJa}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.EddVrWkqZTlvmci instanceof THREE.Mesh
						? nodes.EddVrWkqZTlvmci.geometry
						: undefined
				}
				material={materials.xNrofRCqOXXHVZt}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.KSWlaxBcnPDpFCs instanceof THREE.Mesh
						? nodes.KSWlaxBcnPDpFCs.geometry
						: undefined
				}
				material={materials.yQQySPTfbEJufve}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.TakBsdEjEytCAMK instanceof THREE.Mesh
						? nodes.TakBsdEjEytCAMK.geometry
						: undefined
				}
				material={materials.PaletteMaterial003}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.IykfmVvLplTsTEW instanceof THREE.Mesh
						? nodes.IykfmVvLplTsTEW.geometry
						: undefined
				}
				material={materials.PaletteMaterial004}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.wLfSXtbwRlBrwof instanceof THREE.Mesh
						? nodes.wLfSXtbwRlBrwof.geometry
						: undefined
				}
				material={materials.oZRkkORNzkufnGD}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.WJwwVjsahIXbJpU instanceof THREE.Mesh
						? nodes.WJwwVjsahIXbJpU.geometry
						: undefined
				}
				material={materials.yhcAXNGcJWCqtIS}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.YfrJNXgMvGOAfzz instanceof THREE.Mesh
						? nodes.YfrJNXgMvGOAfzz.geometry
						: undefined
				}
				material={materials.bCgzXjHOanGdTFV}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.DCLCbjzqejuvsqH instanceof THREE.Mesh
						? nodes.DCLCbjzqejuvsqH.geometry
						: undefined
				}
				material={materials.vhaEJjZoqGtyLdo}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.CdalkzDVnwgdEhS instanceof THREE.Mesh
						? nodes.CdalkzDVnwgdEhS.geometry
						: undefined
				}
				material={materials.jlzuBkUzuJqgiAK}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.NtjcIgolNGgYlCg instanceof THREE.Mesh
						? nodes.NtjcIgolNGgYlCg.geometry
						: undefined
				}
				material={materials.PpwUTnTFZJXxCoE}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.pXBNoLiaMwsDHRF instanceof THREE.Mesh
						? nodes.pXBNoLiaMwsDHRF.geometry
						: undefined
				}
				material={materials.yiDkEwDSyEhavuP}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.IkoiNqATMVoZFKD instanceof THREE.Mesh
						? nodes.IkoiNqATMVoZFKD.geometry
						: undefined
				}
				material={materials.hiVunnLeAHkwGEo}
				scale={0.01}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.rqgRAGHOwnuBypi instanceof THREE.Mesh
						? nodes.rqgRAGHOwnuBypi.geometry
						: undefined
				}
				material={materials.HGhEhpqSBZRnjHC}
				scale={0.01}
			/>
		</group>
	);
};

export default Model;

useGLTF.preload("/models/scene.glb");
